In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the dataset  
data = pd.read_csv('dataset_d3_limpio.csv')

In [4]:
data.head()

,datetime,id_casa,produccion_kWh,num_placas,irradiancia_W_m2,temperatura,nubosidad,festivo
0,2017-05-31 01:00:00,1,0.0,4,0.0,19.60,100.0,0
1,2017-05-31 02:00:00,1,0.0,4,0.0,19.50,100.0,0
2,2017-05-31 03:00:00,1,0.0,4,0.0,19.42,100.0,0
3,2017-05-31 04:00:00,1,0.0,4,0.0,19.38,100.0,0
4,2017-05-31 05:00:00,1,0.0,4,0.0,19.39,100.0,0

In [12]:
len(data['id_casa'].unique())

4668

In [11]:
data = data[data['num_placas'] != 0]

In [14]:
# Guardar las primeras 100 casas random
casas = data['id_casa'].unique()
casas = np.random.choice(casas, 100, replace=False)

In [15]:
len(data['id_casa'].unique())

4668

In [17]:
casas

array([ 3234,  2933, 11325,  3878, 14445,  1120, 11852,  7503, 15426,
       14036, 14322,  2309,  1058, 11442,  7912, 11550,  6502, 11399,
        4504,  1428,  4046,  2183,  6386,  1303,  2617, 11846,   638,
         741, 10660, 13752,  9989, 12352,  8002,  5145,  6336, 12477,
        3752, 11523,  8162,  1651,  3315, 10942, 10531,  4937, 14024,
        5684,  7147, 14614, 12814,  1794,  6661, 13435, 12127, 15412,
         762,  5924, 10713,  9677,  9417,  4203, 11718,  4581, 14554,
       13206, 12665,  8284,  9792,  1412,  3647,  5558,  6928, 12657,
        5640,  7493, 14494, 11738,  1627,  4666,  7304,  5551, 15502,
        9888, 15219,  6910,  2367, 14725, 10552, 14674,  7272,  3194,
        4297,    37, 10296,  2329, 11824,  8289, 12447,  1881,  6024,
        4063], dtype=int64)

In [18]:
# Filtrar el DataFrame para mantener solo las filas con las casas seleccionadas
data_filtrado = data[data['id_casa'].isin(casas)]

In [ ]:
len(data_filtrado['id_casa'].unique())

100

In [22]:
# Guardar el DataFrame filtrado en un archivo csv
data_filtrado.to_csv('dataset_d3_filtrado.csv', index=False)

In [23]:
data_filtrado.describe()

,id_casa,produccion_kWh,num_placas,irradiancia_W_m2,temperatura,nubosidad,festivo
count,2.668319e+06,2.668319e+06,2.668319e+06,2.668319e+06,2.668319e+06,2.668319e+06,2.668319e+06
mean,6.961804e+03,1.257329e-01,4.360754e+00,1.442086e+02,1.733252e+01,8.487037e+01,2.740527e-02
std,4.129984e+03,2.412313e-01,2.195611e+00,2.384361e+02,5.136699e+00,2.501545e+01,1.632612e-01
min,3.700000e+01,0.000000e+00,1.000000e+00,0.000000e+00,3.830000e+00,0.000000e+00,0.000000e+00
25%,3.315000e+03,0.000000e+00,2.000000e+00,0.000000e+00,1.309000e+01,7.710000e+01,0.000000e+00
50%,6.661000e+03,0.000000e+00,5.000000e+00,0.000000e+00,1.615000e+01,1.000000e+02,0.000000e+00
75%,1.066000e+04,1.331180e-01,6.000000e+00,2.186500e+02,2.185000e+01,1.000000e+02,0.000000e+00
max,1.550200e+04,1.525056e+00,8.000000e+00,9.531600e+02,3.018000e+01,1.000000e+02,1.000000e+00